package com.carthagoowners.pages

import scalatags._
import com.carthagoowners._
import scala.xml.Unparsed

class May2013GatheringPage extends Page( "gatheringMay2013" )
{
	def customContents() : Seq[HtmlTag] =
	{
	    Seq( 
	        h1( "6th UK Gathering - 2013" ),
	        h2( "Thursday 16th May - Sunday 19th May 2013" ),
	        h3( "Location" ),
	        p( "Summer Ponds, Nr Horsham, Sussex" ),
	        h3( "Summary"),
	        p( "Our Spring Gathering in 2013 was held in the beautiful county of Sussex." ),
	        p( "27 Carthagos gathered at this beautiful campsite and enjoyed an unusual sunny and warm spell in what was rather a wet May." ),
	        h3 ("Report"),
	        h6( "by Roger and Diane Hersee" ),
	        p( "The weather returned to cold and wet, again, with forecasts of more to come. It was mid-May and time to get ready for the spring gathering at Sumners Ponds. This all reminded us of how it had also been just before the Ambleside meeting, last year. But the vagaries of the weather were not going to dissuade us from going, particularly considering that we'd already paid our deposit. We needn't have worried as it turned out better for us for the full duration, just as it had done last year." ),
	        p( "The chosen venue is a popular location for anglers, sporting a number of fishing lakes within its confines. We arrived in plenty of time to look around before the activities started and took some snaps just in case the sun and blue sky did not remain. We saw several fisher people (if that's the current term in a politically correct society) and ducks of many variety, but the fish remained in hiding. There were photos of past big catches on show, just to remove any doubt, so we took their word for the quality of stock lurking below the surface." ),
	        p( "As fishing is said to be the most popular participative sport in the UK, the site has a good market to address and probably did not need an influx of around thirty Carthago motorhomes. Although fully booked, it did not feel crowded and we were made most welcome." ),
	        p( "The fact that we had no fishing tackle did not matter as there was a full itinerary to occupy us and little time to be distracted by the alternative events provided by the site for the other visitors." ),
	        p( scala.xml.Unparsed( "On the Thursday evening we gathered at the lakeside caf&eacute; for refreshments, where we caught up with old friends and met a few new ones." ) ), 
	        img.attr( "src" -> "images/gatheringMay2013/Owners and Coach.jpg", "alt" -> "Owners and Coach", "Width"->"1","Height"->"500" ),
	        p( "On Friday morning we filled a coach and travelled over the Downs towards the coast. A very nice guide, by the name of George, described our surroundings in detail as we passed by numerous points of interest. His knowledge of the local history and geology was profound. George had clearly spent a lot of time in the area, if not on Google. " ),
	        p( "Our first stop was Bosham, just north of Chichester harbour, where we wandered around the quay and had coffee. The road along the front is flooded at high tide and unwary motorists often return to find their parked vehicle inundated. As it was low tide when we arrived we were not entertained by such an event but were greeted by mud flats instead. You could forgive those that are unaware of the danger as the scene at low tide is quite innocent and the sea is nowhere to be seen." ),
	        div(
	            img.attr( "src" -> "images/gatheringMay2013/Bosham.jpg", "alt" -> "Bosham", "class" -> "float_left" ),
	            img.attr( "src" -> "images/gatheringMay2013/Amberley.jpg", "alt" -> "Amberley", "class" -> "float_right" )
            ),
	        p( "From Bosham, we moved on to Arundel for lunch. In a couple of hours we wandered around and saw as much as we could but will need to return to do it justice, although we do now have the tea towel. " ),
	        p( "On our return to base, we detoured slightly to visit the quaint village of Amberley where typical house prices start from 1 million pounds. George directed our proficient coach driver straight through some threatening 6'6 only signs to get us into the centre before turning around. It was not somewhere many of us would have chosen to take our much smaller motorhomes. The properties were, indeed, pretty (expensive and high maintenance). Purchasing one was academic for us, not due to the mortgage required, but because it did not appear to be the kind of place that would entertain the idea of a mobile home on the drive, even if you could conquer the access. We suspect that, if you can afford to live there, you are intended to spend your leisure time in some other way. " ),
	        p( "We were back in time for a substantial meal at the Queen's Head, a local pub just a short walk away. There was no escaping the traditional quiz that followed, nor the heated debates about possible answers. There were no fewer than three quizzes, actually, and one was enough to take the biscuit. We're all friends again now, though. Prizes, kindly donated by VB air suspension, were gratefully received by the winning table. They answered remarkably few questions incorrectly and were leaders by a good margin so that the extra half-mark we felt we might have deserved would still not have made any difference. We hope they enjoy their wine but we're not sure what they'll do with the nodding dog." ),
	        p( "The representatives from VB air suspension and Rosmia remained around to provide help and advice to owners about suspension and mobility aids during the Gathering. We made good use of their time." ),
	        p( "Having extended our normal week-end by two days it took some adjusting to, as we kept thinking we had been gained an extra Saturday. When Saturday finally did arrive we were presented with another difficult question: Do we choose to join the walk led by our very nice guide George, go on a cycle ride, or participate in some retail therapy at Horsham? In the event we chose cycling and we were not alone. George led a good contingent of walkers in the direction of Billinghurst, with the promise of lunch at a pub 'just beyond the next field' in Adversane. Meanwhile, we joined a similar-sized group to be led by Gill and followed by John in the direction of a local water park. It's still not clear why John thought it appropriate to be wearing a yellow jersey, though. " ),
	        img.attr( "src" -> "images/gatheringMay2013/Cyclists.jpg", "alt" -> "Cyclists" ),
	        p( "There was an impressive array of serious equipment to be seen, although one is drawn to wonder at the number of electrically assisted machines amongst the diverse collection of cranks. We navigated our way to Southwater park for a coffee but, on arrival, felt that it might be better to continue along the Downs Link path to a pub recommended by George for our refreshment. We were not sure when George last visited this pub, but it was no longer open for business. It had been gutted and was in the process of being refurbished and transformed into a private dwelling. Undeterred, we pedaled on a few miles more to West Grinstead where we found a very accommodating hostelry. The weather was fine, so we were able to eat outside in an ancient orchard without upsetting the regulars inside. After lunch our party fragmented as some decided to cycle on towards the sea and others to chat for longer before working their way back to the water park for a coffee they'd foregone earlier." ),
	        img.attr( "src" -> "images/gatheringMay2013/Cyclists Lunch.jpg", "alt" -> "Cyclists Lunch" ),
	        p("We chose to go further south and head to the sea. Our route followed the line of a disused railway for most of the way, so it was not easy to get lost. We should, perhaps, not have been so confident about our destination. Only a few miles further on, we suffered a gear problem that we managed to fix after fiddling with cogs and chains for quite a while. Hands were cleaned as best they could be after such endeavours and then we continued. Luck was not on our side. It wasn't long before we picked up a Hawthorn and a puncture to go with it. "),
	        p("We found the puncture outfit and prepared the pump. This should not have taken long. Although hands were moderately clean, the air was soon not. There were no tools to remove the wheel or tyre. Questions were abundant about the last occasion that we had mended a puncture but, even if answers had been forthcoming, they were not going to help resolve the current problem. We looked around for something stout but everything we tried was far too fat or frail. Just like policemen, fellow bikers seemed to be in absence when you need them most. The thought of wheeling a bike with a flat tyre all the way back motivated us to try even harder, so we desperately started to prise with a key. We were only 'almost' getting the tyre to come when a passing cyclist took pity on our plight and lent us two weak plastic levers. Although not ideal, they were much better than nothing, saving our key from total annihilation and enabling a successful repair to be completed. Someone did not want us to reach the sea. We had lost a lot of time and could not risk another mishap in case we missed the evening's activities, so we decided to head back rather than continue our mission."),
	        p("As has often been the problem after our first ride of the season, we were a little tired by the time we had returned and it may have been just as well that our outing was curtailed. We had time to relax and shower before waddling off like John (Wayne) to the Queen's Head where we were fortunate enough to be able to rest our tender buttocks on a fellow owner's car rug instead of the solid benches provided. There were no more challenges for us that evening. Instead we enjoyed another splendid meal, followed by an exceptional variety of music and entertainment from a duo called 'Taxi Home'."),
	        p("In spite of enjoying a long week-end, it was all over much sooner than we'd have wished. We parted at noon on the Sunday after a final meeting and coffee at the lakeside bar."),
	        p("If you've not attended one of the Carthago gatherings they can be recommended. There may not be many to choose from each year but the one near York, next year, sounds like it'll be another worth going to. Past performance can be no guarantee of the future, of course, so the weather may really turn bad next time but be assured that the company will be good."),
	        img.attr( "src" -> "images/gatheringMay2013/Everyone.jpg", "alt" -> "Everyone" )
        )
	}
}