package com.carthagoowners.pages

import scalatags._
import com.carthagoowners._
import scala.xml.Unparsed

class October2008GatheringPage extends Page( "gatheringOctober2008" )
{
	def customContents() : Seq[HtmlTag] =
	{
	    Seq( 
	        h1( "European Gathering - 2008" ),
	        h2( "Thursday 2nd October - Sunday 4th October 2008" ),
	        h3( "Location" ),
	        p( "Camping am Bauernhof, Southern Germany" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Camping Bauernhof Logo.gif", "alt" -> "Camping am Bauernhof Logo" ),
	        h3( "Summary"),
	        p( "" ),
	        p( "28 Carthagos gathered for our first European gathering." ),
	        h3 ("Report"),
	        h6( "by George Pennells" ),
	        p( "28 Carthagos (55 people) arrived at this beautiful campsite in southern Germany.  Many of us had already been touring in Europe and many were on their way to a variety of European destinations after the Gathering." ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 1.jpg", "alt" -> "Carthagos 1 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 2.jpg", "alt" -> "Carthagos 2 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 3.jpg", "alt" -> "Carthagos 3 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 4.jpg", "alt" -> "Carthagos 4 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 5.jpg", "alt" -> "Carthagos 5 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 6.jpg", "alt" -> "Carthagos 6 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Carthagos 7.jpg", "alt" -> "Carthagos 7 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Donkey.jpg", "alt" -> "Donkey Photo", "width" ->"380" ),
	        p( "Rudi and Margrit Kramer were wonderful hosts and went out of their way to ensure we had a great time. They chose to spend the evenings with us so that they could improve their English but in fact their English was considerably better than our German!" ),	        
	        p( "The campsite was quite small, like a Caravan Club CL is some respects, which had superb facilities that were spotlessly clean.  In the evenings we were able to gather together in a chalet which was part of the family farm." ),
	        p( "Most people arrived on Wednesday and Thursday and we all got to know each other over a few bottles of wine and beer. Many, of course, had met at the Inaugural Gathering in Derbyshire but they soon made the newcomers feel welcome and there was quite a buzz as we all met up in the chalet on Thursday evening." ),
		    img.attr( "src" -> "images/gatheringOctober2008/Michaels bus.jpg", "alt" -> "Michaels bus Photo" ),
	        p( <b>Friday</b> ," morning Michael Sterk arrived with a coach and drove us to the first factory visit at Schmalegg where the Mega Liner, M-Liner and Opus models are built. We split into two groups and were shown everything on the production run from making all the furniture (including furniture for the Chic) to the adaption of the chassis and through the final assembly of the motorhomes. It was a public holiday in Germany and so the production line was closed and so we had ample opportunity to look into everything." ),
		    p( " After that we travelled into Ravensburg to the Chic factory.  Here again all was quiet but again we were able to see the full production line which included a large area where the aluminium side panels and roofs are fabricated.  We also had an opportunity to have a close look at the new 3.5t Chic which is to be built in the new Slovenia factory. This new model is very much aimed at the French and other markets where driving licences restrict motorhomes to a maximum of 3.5 tonnes. " ),
		    p( "Everyone agreed that they had really enjoyed the factory visits and that they were impressed with the quality that is put into every Carthago motorhome." ),
		    p( "Michael then drove us into Ravensburg city centre, which again was very quiet due to the public holiday. We had a couple of hours to explore the beautiful old town area and to have some lunch before returning to the campsite." ),
		    img.attr( "src" -> "images/gatheringOctober2008/Ravensburg 1.jpg", "alt" -> "Ravensburg 1 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Ravensburg 2.jpg", "alt" -> "Ravensburg 2 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Ravensburg 3.jpg", "alt" -> "Ravensburg 3 Photo" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Ravensburg 4.jpg", "alt" -> "Ravensburg 4 Photo" ),
		    p( "In the evening Carthago treated us to a magnificent barbeque. There was meat of every kind, salad and rolls and some local specialities and all was washed down with an unending supply of German beer. The Kramer family sons took on the job of beer waiters and as soon as your glass looked empty another one arrived. An excellent evening." ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 1.jpg", "alt" -> "BBQ 1 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 2.jpg", "alt" -> "BBQ 2 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 3.jpg", "alt" -> "BBQ 3 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 4.jpg", "alt" -> "BBQ 4 Photo", "width" ->"380"),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 5.jpg", "alt" -> "BBQ 5 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 6.jpg", "alt" -> "BBQ 6 Photo", "width" ->"380"),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 7.jpg", "alt" -> "BBQ 7 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 8.jpg", "alt" -> "BBQ 8 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 9.jpg", "alt" -> "BBQ 9 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 10.jpg", "alt" -> "BBQ 10 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/BBQ 11.jpg", "alt" -> "BBQ 11 Photo", "width" ->"380" ),
		    p( <b>Saturday</b> , " dawned rainy and our plans for shopping trips in Lindau were rained off, much to the chagrin of the ladies and the delight of the men and a reprieve for the credit cards. Again Michael arrived with the coach and we went off to Freidrichshafen and visited the Zeppelin Museum, which is right on the lakeshore where the ferries depart for Switzerland. The size and luxury of the airships was impressive. When it was time to get back to Michaels coach the heavens opened and most of us arrived soaking wet.  Whilst we were in the Museum Michael had taken the opportunity to reserve tables at a local, hilltop restaurant for lunch. After a short coach journey and we found ourselves at a delightful local restaurant with spectacular views across Lake Constance and into the Alps (or should have been if the cloud wasn't quite so low).  Here we were recommended to sample some of the local speciality dishes which were very tasty. Back on the coach again and off to a Schnapps tasting session at a local fruit farm. 44 people shuffled into the tasting room and several bottles of Schnapps were downed in quick succession. The liquor was truly splendid and the farm made some significant sales with smiling Carthago owners carrying away several bottles each." ),
		    img.attr( "src" -> "images/gatheringOctober2008/Zeppelin 1.jpg", "alt" -> "Zeppelin 1 Photo" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Zeppelin 2.jpg", "alt" -> "Zeppelin 2 Photo" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Schnapps 1.jpg", "alt" -> "Schnapps 1 Photo", "width" ->"380" ),
		    img.attr( "src" -> "images/gatheringOctober2008/Schnapps 2.jpg", "alt" -> "Schnapps 2 Photo", "width" ->"380" ),
		    p( "In the evening a charity raffle was held. The first prize was donated by Carthago and was a voucher for a luxury camp site week for 2 people in the Italian Dolomites at " ),
		    p( "Caravan Park Sexten link" ),		    
		    p( "Included in the prize was a gourmet dinner for two and a 100 euro voucher for use in the wellness facilities.  This prize was won by Russell Farrar and Gill Remmer. A truly wonderful prize - thank you Carthago." ),
		    p( "The second prize was a gift voucher donated by Lowdhams for 100 pounds which could be used in either their accessories shop or their service department.  This was won by Peter and Barbara Lamb. A generous gift - thank you Lowdhams." ),
		    p( "There was a third prize of a shoulder cooler bag carrier together with a bottle of wine and two glasses for a romantic lunch at some exotic location which was won by Norman and Georgina Britton. " ),
		    p( "A fourth prize of a bottle of wine which was kindly donated by Ken and Georgina Hudson was won by Peter and Jean Dunbar." ),
		    p( "The sale of the raffle tickets raised 258 euro for charity and everyone's preferred charity was put into a hat. The winning charity, picked out of the hat, was " ),
		    p( "Christina Noble Foundation" ),
		    p( "which was nominated by Peter and Barbara Lamb.  Thank you to everyone for your generous donations. The Christina Noble Foundation have promised a brief article for our next newsletter." ),
		    p( "Russell and Gill have also promised to let us know all about Caravan Park Sexten." ),
		    img.attr( "src" -> "images/gatheringOctober2008/Raffle.jpg", "alt" -> "Raffle Photo" ),
	        h6("Sunday"),
		    p( "This was departure day and we reluctantly said goodbye to the campsite, who had looked after us so well, and to our friends old and new. All agreed that despite the weather, the weekend had been a huge success and they looked forward to joining the Gatherings in 2009. " ),
		    p( "Many who were not at the May meeting and so coming together for the first time told us that they were a little hesitant as the were not rally type people but that they had really enjoyed themselves and would come again another time as everything was so informal." ),
	        img.attr( "src" -> "images/gatheringOctober2008/Last Morning 1.jpg", "alt" -> "Last Morning 1 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Last Morning 2.jpg", "alt" -> "Last Morning 2 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Last Morning 3.jpg", "alt" -> "Last Morning 3 Photo", "width" ->"380" ),
	        img.attr( "src" -> "images/gatheringOctober2008/Last Morning 4.jpg", "alt" -> "Last Morning 4 Photo", "width" ->"380" ),
		    p( "Thank You" ),
		    ul,
		    li( "- To everybody that came along to the German Gathering. It was you who made it such a great event.  We hope to see even more of our members at our Gatherings in 2009." ),
		    li( "- To Michael Sterk and Carthago for putting on a really special event; for making us feel so welcome and for looking after us so well." ),
		    li( "- The Familie Kramer for providing such a pleasant and enjoyable environment and for making sure that we all enjoyed ourselves." ),
		    li( "- To Ian Brown of Lowdhams for making a special trip to join us in Germany and to meet with his customers." ),
		    p( "" )
        )
	}
}